### ISSUE TITLE
I have an error when I try to use the unsubscribeFromMarketData function

### ISSUE THREAD

**Issue by esepeasodegabi** [agiliumtrade-ai/metaapi-node.js-sdk#34]
My code is:

```
const subscriptions = this.connection.subscriptions(symbol)
try {
    this.connection.unsubscribeFromMarketData(symbol,subscriptions )
} catch (err) { 
    console.error(err)
}
```

C:\Users\gabic\Documents\XXX\node_modules\metaapi.cloud-sdk\lib\clients\metaApi\metaApiWebsocket.client.es6:1576
      return new ValidationError(data.message, data.details);
             ^
ValidationError: Validation failed
    at MetaApiWebsocketClient._convertError (C:\Users\gabic\Documents\XXX\node_modules\metaapi.cloud-sdk\lib\clients\metaApi\metaApiWebsocket.client.es6:1576:14)
    at Socket.<anonymous> (C:\Users\gabic\Documents\XXX\node_modules\metaapi.cloud-sdk\lib\clients\metaApi\metaApiWebsocket.client.es6:430:34)
    at Socket.Emitter.emit (C:\Users\gabic\Documents\XXX\node_modules\component-emitter\index.js:145:20)
    at Socket.onevent (C:\Users\gabic\Documents\XXX\node_modules\socket.io-client\lib\socket.js:278:10)
    at Socket.onpacket (C:\Users\gabic\Documents\XXX\node_modules\socket.io-client\lib\socket.js:236:12)
    at Manager.<anonymous> (C:\Users\gabic\Documents\XXX\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (C:\Users\gabic\Documents\XXX\node_modules\component-emitter\index.js:145:20)
    at Manager.ondecoded (C:\Users\gabic\Documents\XXX\node_modules\socket.io-client\lib\manager.js:349:8)
    at Decoder.<anonymous> (C:\Users\gabic\Documents\XXX\node_modules\component-bind\index.js:21:15)
    at Decoder.Emitter.emit (C:\Users\gabic\Documents\XXX\node_modules\component-emitter\index.js:145:20)

**Comment by RomanKisilenko** [comment]
Please provide the full exception details including exception payload (details field). Please also provide full details about the request you are making (the exact values of unsubscribeFromMarketData arguments)

**Comment by esepeasodegabi** [comment]
I've been doing some more research and testing, and this error only occurs when some value is entered for the 'intervalInMilliseconds' parameter of the MarketDataSubscription object (in my case I used 5000). If you put this value in both the subscribeToMarketData method (here it works correctly), but it generates the error that I reported.
Specifically, we get a message from server socket like this:

42["processingError",{"id":25633,"error":"ValidationError","message":"Validation failed","details":[{"parameter":"subscriptions[0].intervalInMilliseconds","value":5000,"message":"Unexpected value."}],"requestId":"PWg55IELnrxT7mYoV8UDOAT9DEtWDKBB"}]`

The exact parameters I used were
symbol: 'EURUSD'
subscriptions: [{type: 'candles', timeframe: '1m', intervalInMilliseconds: 5000}]

**Comment by RomanKisilenko** [comment]
In this case this is a bug in your code as the method expects array of these objects as a second argument: https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/master/lib/clients/metaApi/metaApiWebsocket.client.d.ts#L1229-L1238
